### ISSUE TITLE
Which folder is being used?

### ISSUE THREAD

**Issue by mozo78** [hamidzr/webcam-mods#16]
Hello,
Im wondering which folder/s I have to chown in order to be able to use it without root permissions?
Thank you very much :)

**Comment by hamidzr** [comment]
you shouldn't need to need root other than for setting up your webcam device and/or adding the kernel modules especially if you're not installing the python package globally. 🤔

**Comment by mozo78** [comment]
When it adds the video device (everytime you start the stream), it always asks for root permissions. For now I use it this way for I don't want my coleagues to enter a password manually:
`cd "`dirname "$0"`"/webcam-mods-master && pipenv run echo "1234" | sudo -S make add-video-dev
pipenv run python entry.py bg-swap`
1234 is the password.
But my boss have problems with the fact they have admin rights. They should be standard users and here comes the problem - they can't start the stream as a standard user.

**Comment by hamidzr** [comment]
adding the video device does require root access and I'm not sure how you can get around that off the top of my head. running the script however should not require  root access.

you can set up your machine to add this virtual device on startup (https://askubuntu.com/a/1245223) . take the exact arguments from the Makefile for this project.

with this set up once the machine boots up you'll have the virtual device set up and should be able to use the project without root access. However, since I moved the project to use `pyvirtualcam` it seems to mess with the device (maybe I'm using it incorrectly) after the script shuts down so the next time you'd try to start the script you basically have to tear down and recreate the device this wasn't the case when I was directly using the v4l2 driver and I'm not sure how to fix this part.

**Comment by mozo78** [comment]
Thank you very much. I hope pyvirtualcam will be fixed :)

**Comment by hamidzr** [comment]
> However, since I moved the project to use pyvirtualcam it seems to mess with the device (maybe I'm using it incorrectly) after the script shuts down so the next time you'd try to start the script you basically have to tear down and recreate the device this wasn't the case when I was directly using the v4l2 driver and I'm not sure how to fix this part.

this is now addressed on Linux by switching back to the previous v4l2loopback backend I was using.
